# Generated by Django 2.2.1 on 2019-05-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reisesName', models.CharField(max_length=20)),
                ('reisesCategory', models.CharField(max_length=20)),
                ('reisesNumber', models.CharField(max_length=20)),
            ],
        ),
    ]
